version: "3.9"
services:
  odoo:
    image: odoo:14
    restart: always
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons

  db:
    image: postgres:10
    restart: always
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data:
