/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Client;

import Client.RestService.RestService;
import org.apache.xmlrpc.XmlRpcException;

import java.io.IOException;

public class App {
    public static void main(String[] args) throws IOException, XmlRpcException {
        RestService restService = new RestService();
        //restService.setUrl("https://jsonplaceholder.typicode.com/");
        //restService.setUrl("https://s3.amazonaws.com/dolartoday/");
        restService.testOdooGetRequest();
        //restService.getFieldsOdooModel("stock.quant");
        //restService.sendGetRequest("data.json");
    }
}
